//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlacePick.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audio
    {
        public Audio()
        {
            this.Points = new HashSet<Point>();
        }
    
        public int id { get; set; }
        public string Guid { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<Point> Points { get; set; }
    }
}
