//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlacePick.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public Point()
        {
            this.Audios = new HashSet<Audio>();
            this.Images = new HashSet<Image>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<int> AudioId { get; set; }
        public int RouteId { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual ICollection<Audio> Audios { get; set; }
        public virtual ICollection<Image> Images { get; set; }
    }
}
